/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tjcs.venture;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.tjcs.venture.Utilities.Columns;

/**
 *
 * @author dougthompson
 */
public class ImportIssuesDialog extends javax.swing.JDialog {

    /**
     * Creates new form ImportIssuesDialog
     */
    public ImportIssuesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parentFrame = (LotteryFrame) (JFrame) parent;
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPaneInvalidRecords = new javax.swing.JScrollPane();
        jTableInvalidRecords = new javax.swing.JTable();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("The following records could not be imported.  Please check the spreadsheet data and adjust accordingly.");
        jScrollPane1.setViewportView(jTextArea1);

        jTableInvalidRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneInvalidRecords.setViewportView(jTableInvalidRecords);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneInvalidRecords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonOK)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneInvalidRecords, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportIssuesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportIssuesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportIssuesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportIssuesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImportIssuesDialog dialog = new ImportIssuesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneInvalidRecords;
    private javax.swing.JTable jTableInvalidRecords;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
    private final LotteryFrame parentFrame;
    List<XSSFRow> problemRows = new ArrayList<>();

    private void initMyComponents() {
        //buildTable();
    }

    public void setProblemRows(List<XSSFRow> problemRows) {
        this.problemRows = problemRows;
    }
    
    public void buildTable() {
        List<DB_RecordCell> dbRecordCellList = new ArrayList<>();
        JTableProspectiveStudents prospectiveStudentsTable;
        prospectiveStudentsTable = new JTableProspectiveStudents();
        String[] headerCols = new String[] {"Row",
                                            Columns.LAST_NAME.getColumnName(),
                                            Columns.FIRST_NAME.getColumnName(),
                                            Columns.TIER.getColumnName(),
                                            Columns.GRADE.getColumnName(),
                                            Columns.FAMILY_KEY.getColumnName()};

        prospectiveStudentsTable.setTableHeaderRow(headerCols);
        
        int lastNameColIndex = Utilities.Columns.getColumnIndex(Utilities.Columns.LAST_NAME);
        int firstNameColIndex = Utilities.Columns.getColumnIndex(Utilities.Columns.FIRST_NAME);
        int tierColIndex = Utilities.Columns.getColumnIndex(Utilities.Columns.TIER);
        int gradeColIndex = Utilities.Columns.getColumnIndex(Utilities.Columns.GRADE);
        int familyKeyColIndex = Utilities.Columns.getColumnIndex(Utilities.Columns.LAST_NAME);
        
        int rowCounter = 0;
        
        for (XSSFRow row : problemRows) {
            int colCounter = 0;
            DB_RecordCell tempCell = new DB_RecordCell(String.valueOf(row.getRowNum()), rowCounter, colCounter);
            dbRecordCellList.add(tempCell);
            tempCell = getCellValue(row, lastNameColIndex, rowCounter, colCounter++);
            dbRecordCellList.add(tempCell);
            tempCell = getCellValue(row, firstNameColIndex, rowCounter, colCounter++);
            dbRecordCellList.add(tempCell);
            tempCell = getCellValue(row, tierColIndex, rowCounter, colCounter++);
            dbRecordCellList.add(tempCell);
            tempCell = getCellValue(row, gradeColIndex, rowCounter, colCounter++);
            dbRecordCellList.add(tempCell);
            tempCell = getCellValue(row, familyKeyColIndex, rowCounter, colCounter++);
            dbRecordCellList.add(tempCell);
            rowCounter++;
        }
        
        Object[][] tableItems = new Object[rowCounter][6];
        
        rowCounter = 0;
        int colCounter = 0;
        for (DB_RecordCell dB_RecordCell : dbRecordCellList) {
            tableItems[rowCounter][colCounter++] = dB_RecordCell;
            if (colCounter > 5) {
                rowCounter ++;
                colCounter = 0;
            }
        }
        
        prospectiveStudentsTable.setProspectiveStudents(tableItems);
        prospectiveStudentsTable.setTableHeaderRow(headerCols);
        prospectiveStudentsTable.initTable();
        jScrollPaneInvalidRecords.setViewportView(prospectiveStudentsTable);
    }
    
    private DB_RecordCell getCellValue(XSSFRow row, int colIndex, int rowCounter, int colCounter) {
        if (row == null || colIndex < 0 || rowCounter < 0 || colCounter < 0) return null;
        String tempValue = "";
        if (row.getCell(colIndex) != null) {
            tempValue = row.getCell(colIndex).toString();
        }
        return new DB_RecordCell(tempValue, rowCounter, colCounter);
    }

    @Override
    public void dispose() {
        parentFrame.resetCursor();
        super.dispose();
    }
    
}
